# Generated by Django 4.0 on 2022-01-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0002_alter_user_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='exam_category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='exam_category',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='exam_category',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='major',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='major',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='major',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='result',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='result',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='school',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='section',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_details',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_details',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_details',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user'),
        ),
    ]
