# Generated by Django 4.0 on 2021-12-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0003_class_details_school_alter_user_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_details',
            options={'verbose_name': 'Class_Detail', 'verbose_name_plural': 'Class_Details'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': 'major', 'verbose_name_plural': 'majors'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'standard', 'verbose_name_plural': 'standards'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
