# Generated by Django 4.0 on 2021-12-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0004_alter_class_details_options_alter_major_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_major', to='vertos.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='vertos.class_details'),
        ),
    ]
