# Generated by Django 4.0 on 2021-12-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0006_staff_subject_staff_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching_Staff_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('class_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_class', to='vertos.class_details')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_detail', to='vertos.staff')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_subject', to='vertos.subject')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vertos.user')),
            ],
            options={
                'verbose_name': 'staff-detail',
                'verbose_name_plural': 'staff-details',
            },
        ),
        migrations.DeleteModel(
            name='Staff_Details',
        ),
    ]
