# Generated by Django 4.0 on 2022-01-10 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0016_alter_result_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='standard_name',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
