# Generated by Django 4.0.1 on 2022-01-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0018_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage',
            name='distinct_percentage',
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='firstclass_percentage',
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='pass_percentage',
        ),
    ]
