# Generated by Django 4.0.1 on 2022-01-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0019_remove_percentage_distinct_percentage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Percentage',
        ),
    ]
