# Generated by Django 4.0 on 2022-01-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0021_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Percentage',
        ),
    ]
