# Generated by Django 4.0 on 2022-01-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertos', '0022_delete_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='founder',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUD', 'Student'), ('T-S', 'Teaching-Staff'), ('NT-S', 'NonTeaching-Staff')], default='STUD', max_length=10),
        ),
    ]
